import type { EnemyDef } from "../types.js";

export const ENEMIES: EnemyDef[] = [
  // Floor 1 — fodder
  {
    id: "slime",
    name: "Cave Slime",
    hp: 30,
    damage: 4,
    speed: 80,
    attackCooldownMs: 1200,
    attackRange: 36,
    xpReward: 12,
    goldReward: 8,
    ai: "chaser",
    floor: 1,
    color: "#22c55e",
    radius: 18,
  },
  {
    id: "rat",
    name: "Giant Rat",
    hp: 22,
    damage: 5,
    speed: 140,
    attackCooldownMs: 900,
    attackRange: 30,
    xpReward: 14,
    goldReward: 9,
    ai: "chaser",
    floor: 1,
    color: "#a16207",
    radius: 14,
  },
  {
    id: "bat",
    name: "Cave Bat",
    hp: 18,
    damage: 4,
    speed: 160,
    attackCooldownMs: 800,
    attackRange: 32,
    xpReward: 14,
    goldReward: 9,
    ai: "charger",
    floor: 1,
    color: "#475569",
    radius: 12,
  },

  // Floor 2 — basic combat
  {
    id: "skeleton",
    name: "Skeleton",
    hp: 45,
    damage: 7,
    speed: 100,
    attackCooldownMs: 1000,
    attackRange: 40,
    xpReward: 22,
    goldReward: 14,
    ai: "chaser",
    floor: 2,
    color: "#e2e8f0",
    radius: 18,
  },
  {
    id: "goblin_archer",
    name: "Goblin Archer",
    hp: 32,
    damage: 8,
    speed: 90,
    attackCooldownMs: 1400,
    attackRange: 240,
    xpReward: 24,
    goldReward: 16,
    ai: "kiter",
    floor: 2,
    color: "#65a30d",
    radius: 16,
  },
  {
    id: "spider",
    name: "Pit Spider",
    hp: 40,
    damage: 6,
    speed: 130,
    attackCooldownMs: 900,
    attackRange: 34,
    xpReward: 22,
    goldReward: 14,
    ai: "charger",
    floor: 2,
    color: "#7c3aed",
    radius: 16,
  },

  // Floor 3 — heavier hits
  {
    id: "zombie",
    name: "Lurching Zombie",
    hp: 70,
    damage: 10,
    speed: 70,
    attackCooldownMs: 1100,
    attackRange: 40,
    xpReward: 36,
    goldReward: 22,
    ai: "chaser",
    floor: 3,
    color: "#16a34a",
    radius: 20,
  },
  {
    id: "ghoul",
    name: "Ghoul",
    hp: 60,
    damage: 12,
    speed: 130,
    attackCooldownMs: 850,
    attackRange: 38,
    xpReward: 38,
    goldReward: 24,
    ai: "charger",
    floor: 3,
    color: "#7f1d1d",
    radius: 18,
  },
  {
    id: "mage_acolyte",
    name: "Cultist Acolyte",
    hp: 55,
    damage: 14,
    speed: 100,
    attackCooldownMs: 1300,
    attackRange: 260,
    xpReward: 40,
    goldReward: 26,
    ai: "kiter",
    floor: 3,
    color: "#0ea5e9",
    radius: 18,
  },

  // Floor 4 — elites territory
  {
    id: "wraith",
    name: "Wraith",
    hp: 80,
    damage: 16,
    speed: 150,
    attackCooldownMs: 1000,
    attackRange: 240,
    xpReward: 60,
    goldReward: 40,
    ai: "kiter",
    floor: 4,
    color: "#94a3b8",
    radius: 18,
  },
  {
    id: "knight_fallen",
    name: "Fallen Knight",
    hp: 130,
    damage: 18,
    speed: 100,
    attackCooldownMs: 1100,
    attackRange: 44,
    xpReward: 70,
    goldReward: 50,
    ai: "chaser",
    floor: 4,
    color: "#1e293b",
    radius: 22,
  },
  {
    id: "minotaur",
    name: "Minotaur",
    hp: 160,
    damage: 22,
    speed: 110,
    attackCooldownMs: 900,
    attackRange: 50,
    xpReward: 90,
    goldReward: 70,
    ai: "charger",
    floor: 4,
    color: "#92400e",
    radius: 24,
  },

  // Floor 5 — pre-boss elites
  {
    id: "lich",
    name: "Lich",
    hp: 200,
    damage: 24,
    speed: 90,
    attackCooldownMs: 1200,
    attackRange: 280,
    xpReward: 130,
    goldReward: 100,
    ai: "summoner",
    floor: 5,
    color: "#a855f7",
    radius: 22,
  },
  {
    id: "demon_brute",
    name: "Demon Brute",
    hp: 240,
    damage: 28,
    speed: 110,
    attackCooldownMs: 1000,
    attackRange: 48,
    xpReward: 150,
    goldReward: 120,
    ai: "charger",
    floor: 5,
    color: "#dc2626",
    radius: 26,
  },

  // Final boss
  {
    id: "dungeon_lord",
    name: "The Dungeon Lord",
    hp: 480,
    damage: 32,
    speed: 130,
    attackCooldownMs: 800,
    attackRange: 260,
    xpReward: 400,
    goldReward: 350,
    ai: "summoner",
    floor: 5,
    color: "#f59e0b",
    radius: 30,
  },
];

export const enemiesById: Record<string, EnemyDef> = Object.fromEntries(
  ENEMIES.map((e) => [e.id, e])
);
