import type { ItemDef } from "../types.js";

export const ITEMS: ItemDef[] = [
  // ---------------- Weapons (each maps to a move) ----------------
  {
    id: "wpn_rusty_sword",
    name: "Rusty Sword",
    slot: "weapon",
    rarity: "common",
    basePrice: 40,
    stats: { damage: 2 },
    moveId: "slash",
    description: "Better than fists. Barely.",
  },
  {
    id: "wpn_iron_sword",
    name: "Iron Sword",
    slot: "weapon",
    rarity: "uncommon",
    basePrice: 110,
    stats: { damage: 5 },
    moveId: "slash",
    description: "A reliable blade.",
  },
  {
    id: "wpn_warhammer",
    name: "Iron Warhammer",
    slot: "weapon",
    rarity: "rare",
    basePrice: 220,
    stats: { damage: 8 },
    moveId: "heavy_swing",
    description: "Heavy. Slow. Painful.",
  },
  {
    id: "wpn_rapier",
    name: "Duelist's Rapier",
    slot: "weapon",
    rarity: "uncommon",
    basePrice: 130,
    stats: { damage: 3, critChance: 0.08 },
    moveId: "rapier_thrust",
    description: "Fast pierces. Lethal in skilled hands.",
  },
  {
    id: "wpn_shortbow",
    name: "Hunter's Shortbow",
    slot: "weapon",
    rarity: "uncommon",
    basePrice: 140,
    stats: { damage: 4 },
    moveId: "arrow",
    description: "A trusted ranger's tool.",
  },
  {
    id: "wpn_crossbow",
    name: "Heavy Crossbow",
    slot: "weapon",
    rarity: "rare",
    basePrice: 260,
    stats: { damage: 7 },
    moveId: "crossbow_bolt",
    description: "Punches through plate.",
  },
  {
    id: "wpn_fire_staff",
    name: "Staff of Cinders",
    slot: "weapon",
    rarity: "rare",
    basePrice: 280,
    stats: { damage: 6 },
    moveId: "fireball",
    description: "Smolders at the tip.",
  },
  {
    id: "wpn_frost_wand",
    name: "Frost Wand",
    slot: "weapon",
    rarity: "uncommon",
    basePrice: 160,
    stats: { damage: 4 },
    moveId: "frost_lance",
    description: "Cold to the touch.",
  },
  {
    id: "wpn_arcane_focus",
    name: "Arcane Focus",
    slot: "weapon",
    rarity: "common",
    basePrice: 60,
    stats: { damage: 2 },
    moveId: "arcane_bolt",
    description: "A novice mage's tool.",
  },
  {
    id: "wpn_battle_axe",
    name: "Battleaxe",
    slot: "weapon",
    rarity: "uncommon",
    basePrice: 150,
    stats: { damage: 5 },
    moveId: "axe_cleave",
    description: "Built for cleaving lines.",
  },
  {
    id: "wpn_shuriken_set",
    name: "Shuriken Bandolier",
    slot: "weapon",
    rarity: "rare",
    basePrice: 240,
    stats: { damage: 3, moveSpeed: 0.1 },
    moveId: "shuriken",
    description: "Strapped with razored stars.",
  },
  {
    id: "wpn_thunder_blade",
    name: "Thunderbrand",
    slot: "weapon",
    rarity: "epic",
    basePrice: 540,
    stats: { damage: 10, critChance: 0.05 },
    moveId: "lightning",
    description: "Hums with stored lightning.",
  },
  {
    id: "wpn_void_spear",
    name: "Voidpiercer",
    slot: "weapon",
    rarity: "legendary",
    basePrice: 1100,
    stats: { damage: 16, lifesteal: 0.05 },
    moveId: "void_spear",
    description: "Forged where stars die.",
  },

  // ---------------- Armour ----------------
  {
    id: "arm_cloth",
    name: "Cloth Tunic",
    slot: "armour",
    rarity: "common",
    basePrice: 30,
    stats: { hp: 10, defense: 1 },
    description: "Sturdier than skin.",
  },
  {
    id: "arm_leather",
    name: "Leather Cuirass",
    slot: "armour",
    rarity: "uncommon",
    basePrice: 120,
    stats: { hp: 25, defense: 3 },
    description: "Light, dependable.",
  },
  {
    id: "arm_chain",
    name: "Chainmail",
    slot: "armour",
    rarity: "rare",
    basePrice: 280,
    stats: { hp: 40, defense: 6 },
    description: "Rings interlocked.",
  },
  {
    id: "arm_plate",
    name: "Knight's Plate",
    slot: "armour",
    rarity: "epic",
    basePrice: 600,
    stats: { hp: 70, defense: 10, moveSpeed: -0.1 },
    description: "Heavy but reliable.",
  },

  // ---------------- Helmet ----------------
  {
    id: "hel_hood",
    name: "Wool Hood",
    slot: "helmet",
    rarity: "common",
    basePrice: 25,
    stats: { hp: 4 },
    description: "Keeps the rain off.",
  },
  {
    id: "hel_coif",
    name: "Mail Coif",
    slot: "helmet",
    rarity: "uncommon",
    basePrice: 90,
    stats: { hp: 10, defense: 1 },
    description: "Protects the skull.",
  },
  {
    id: "hel_helm",
    name: "Steel Helm",
    slot: "helmet",
    rarity: "rare",
    basePrice: 220,
    stats: { hp: 18, defense: 2, critChance: 0.05 },
    description: "Reinforced for impact.",
  },

  // ---------------- Boots ----------------
  {
    id: "bts_sandals",
    name: "Worn Sandals",
    slot: "boots",
    rarity: "common",
    basePrice: 20,
    stats: { moveSpeed: 0.05 },
    description: "Cheap. Functional.",
  },
  {
    id: "bts_leather",
    name: "Leather Boots",
    slot: "boots",
    rarity: "uncommon",
    basePrice: 100,
    stats: { moveSpeed: 0.1, hp: 5 },
    description: "Quiet on stone floors.",
  },
  {
    id: "bts_swift",
    name: "Swiftstride Boots",
    slot: "boots",
    rarity: "rare",
    basePrice: 260,
    stats: { moveSpeed: 0.2 },
    description: "A blur with every step.",
  },

  // ---------------- Off-hand ----------------
  {
    id: "off_buckler",
    name: "Wooden Buckler",
    slot: "offhand",
    rarity: "common",
    basePrice: 35,
    stats: { defense: 2 },
    description: "Small but useful.",
  },
  {
    id: "off_kite",
    name: "Kite Shield",
    slot: "offhand",
    rarity: "uncommon",
    basePrice: 130,
    stats: { defense: 5, hp: 10 },
    description: "Covers most of the torso.",
  },
  {
    id: "off_tome",
    name: "Tome of Focus",
    slot: "offhand",
    rarity: "rare",
    basePrice: 240,
    stats: { damage: 3, critChance: 0.05 },
    description: "Sharpens the mind.",
  },

  // ---------------- Ring ----------------
  {
    id: "rng_copper",
    name: "Copper Band",
    slot: "ring",
    rarity: "common",
    basePrice: 40,
    stats: { goldBonus: 0.05 },
    description: "A merchant's trinket.",
  },
  {
    id: "rng_scholar",
    name: "Scholar's Ring",
    slot: "ring",
    rarity: "rare",
    basePrice: 260,
    stats: { xpBonus: 0.15 },
    description: "Memory sharpens.",
  },

  // ---------------- Amulet ----------------
  {
    id: "amu_bone",
    name: "Bone Charm",
    slot: "amulet",
    rarity: "common",
    basePrice: 30,
    stats: { hp: 6 },
    description: "Carved from old bone.",
  },
  {
    id: "amu_vampire",
    name: "Vampiric Locket",
    slot: "amulet",
    rarity: "epic",
    basePrice: 580,
    stats: { lifesteal: 0.08 },
    description: "Drinks deep.",
  },

  // ---------------- Banner (cosmetic) ----------------
  {
    id: "ban_blue",
    name: "Azure Banner",
    slot: "banner",
    rarity: "common",
    basePrice: 50,
    stats: {},
    bannerColor: "#3b82f6",
    description: "A simple azure standard.",
  },
  {
    id: "ban_crimson",
    name: "Crimson Banner",
    slot: "banner",
    rarity: "uncommon",
    basePrice: 150,
    stats: {},
    bannerColor: "#ef4444",
    description: "Bold and unmistakable.",
  },
  {
    id: "ban_gold",
    name: "Golden Standard",
    slot: "banner",
    rarity: "legendary",
    basePrice: 900,
    stats: {},
    bannerColor: "#f59e0b",
    description: "Reserved for champions.",
  },
];

export const itemsById: Record<string, ItemDef> = Object.fromEntries(
  ITEMS.map((i) => [i.id, i])
);

export const RARITY_WEIGHTS: Record<string, number> = {
  common: 60,
  uncommon: 25,
  rare: 10,
  epic: 4,
  legendary: 1,
};

export const STARTING_ITEMS: string[] = [
  "wpn_rusty_sword",
  "arm_cloth",
  "bts_sandals",
  "ban_blue",
];
