import type { MoveDef } from "../types.js";

export const MOVES: MoveDef[] = [
  {
    id: "slash",
    name: "Slash",
    baseDamage: 8,
    cooldownMs: 500,
    projectileSpeed: 0,
    range: 60,
    description: "A quick melee slash.",
  },
  {
    id: "heavy_swing",
    name: "Heavy Swing",
    baseDamage: 18,
    cooldownMs: 1100,
    projectileSpeed: 0,
    range: 75,
    description: "Slow but heavy melee swing.",
  },
  {
    id: "rapier_thrust",
    name: "Rapier Thrust",
    baseDamage: 6,
    cooldownMs: 320,
    projectileSpeed: 0,
    range: 70,
    description: "Lightning-fast pierce.",
  },
  {
    id: "arrow",
    name: "Arrow Shot",
    baseDamage: 10,
    cooldownMs: 600,
    projectileSpeed: 520,
    range: 480,
    description: "Fire a swift arrow.",
  },
  {
    id: "crossbow_bolt",
    name: "Crossbow Bolt",
    baseDamage: 16,
    cooldownMs: 900,
    projectileSpeed: 640,
    range: 520,
    description: "Heavy bolt with knockback.",
  },
  {
    id: "fireball",
    name: "Fireball",
    baseDamage: 22,
    cooldownMs: 1100,
    projectileSpeed: 380,
    range: 460,
    description: "Lobs a fiery orb.",
  },
  {
    id: "frost_lance",
    name: "Frost Lance",
    baseDamage: 14,
    cooldownMs: 700,
    projectileSpeed: 460,
    range: 480,
    description: "A piercing icicle.",
  },
  {
    id: "arcane_bolt",
    name: "Arcane Bolt",
    baseDamage: 11,
    cooldownMs: 500,
    projectileSpeed: 540,
    range: 460,
    description: "Steady mana missile.",
  },
  {
    id: "axe_cleave",
    name: "Axe Cleave",
    baseDamage: 14,
    cooldownMs: 750,
    projectileSpeed: 0,
    range: 70,
    description: "Wide cleaving arc.",
  },
  {
    id: "shuriken",
    name: "Shuriken",
    baseDamage: 6,
    cooldownMs: 280,
    projectileSpeed: 600,
    range: 380,
    description: "Rapid throwing star.",
  },
  {
    id: "lightning",
    name: "Chain Lightning",
    baseDamage: 26,
    cooldownMs: 1300,
    projectileSpeed: 720,
    range: 500,
    description: "Crackling bolt of energy.",
  },
  {
    id: "void_spear",
    name: "Void Spear",
    baseDamage: 34,
    cooldownMs: 1400,
    projectileSpeed: 560,
    range: 520,
    description: "A spear of pure void.",
  },
];

export const movesById: Record<string, MoveDef> = Object.fromEntries(
  MOVES.map((m) => [m.id, m])
);
